name: build

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install --production --ignore-scripts
      - run: zip -R dist.zip ./* .* -X "dist.zip" -X ".git"
      - uses: actions/upload-artifact@v1
        with:
          name: dist.zip
          path: ./dist.zip
      
    
